[[feeds]]
id = "english"
display_name = "English"
description = "A feed of Bluesky posts written in English"
avatar_path = "./assets/avatar.png"
languages = ["en", "en-US", "en-GB", "en-AU", "en-CA", "en-NZ", "en-ZA"]

[[feeds]]
id = "nynorsk"
display_name = "Nynorsk"
description = "A feed of Bluesky posts written in Norwegian nynorsk"
avatar_path = "./assets/avatar.png"
languages = ["nn"]

[[feeds]]
id = "sami"
display_name = "Sami"
description = "A feed of Bluesky posts written in Sami"
avatar_path = "./assets/avatar.png"
languages = ["se"]

[[feeds]]
id = "all"
display_name = "Norsk (Norwegian)"
description = "A feed of Bluesky posts written in Norwegian bokmål, nynorsk and sami"
avatar_path = "./assets/avatar.png"
languages = ["nb", "nn", "no", "se"]

[[feeds]]
id = "tv-shows"
display_name = "Norwegian TV Shows"
description = "A feed of Bluesky posts about Norwegian TV shows"
avatar_path = "./assets/avatar.png"
languages = ["nb", "nn", "no"]
keywords = [
    "tv-serie*",
    "nrk",
    "tv2",
    "netflix",
    "stream*",
    "\"beste serie*\"",
    "\"favoritt serie*\"",
    "\"streaming\" NOT \"problem\""
]
exclude_keywords = [
    "podcast*",
    "radio*",
    "\"teknisk problem*\"",
]

[[feeds]]
id = "tech"
display_name = "Norwegian Tech"
description = "A feed of Bluesky posts about technology in Norwegian"
avatar_path = "./assets/avatar.png"
languages = ["nb", "nn", "no"]
keywords = [
    "teknologi*",
    "kunstig intelligens",
    "programmering",
    "åpen kildekode"
]
