version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: norsky-postgres-prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: norsky
      POSTGRES_USER: norsky
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Database password required}
      POSTGRES_INITDB_ARGS: "--data-checksums"
      POSTGRES_SHARED_BUFFERS: 2GB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 6GB
      POSTGRES_WORK_MEM: 16MB
      POSTGRES_MAINTENANCE_WORK_MEM: 512MB
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U norsky"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: norsky-pgadmin-prod
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:?PgAdmin email required}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:?PgAdmin password required}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'True'
    ports:
      - "127.0.0.1:5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  backup:
    image: prodrigestivill/postgres-backup-local:17-alpine
    container_name: norsky-backup
    restart: unless-stopped
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB:-norsky}
      POSTGRES_USER: ${POSTGRES_USER:-norsky}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SCHEDULE: '@daily'
      BACKUP_KEEP_DAYS: 7
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 6
      HEALTHCHECK_PORT: 8080
    volumes:
      - postgres_backups:/backups
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M

  norsky:
    image: ghcr.io/snorremd/norsky:v2
    container_name: norsky-prod
    restart: unless-stopped
    environment:
      NORSKY_HOST: ${NORSKY_HOST}
      NORSKY_DB_HOST: postgres
      NORSKY_DB_PORT: 5432
      NORSKY_DB_USER: ${POSTGRES_USER:-norsky}
      NORSKY_DB_PASSWORD: ${POSTGRES_PASSWORD}
      NORSKY_DB_NAME: ${POSTGRES_DB:-norsky}
      NORSKY_CONFIG: "/config/feeds.toml"
    volumes:
      - ./feeds.toml:/config/feeds.toml:ro
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

volumes:
  postgres_data:
  pgadmin_data:
  postgres_backups:
