name: Pull Request

on:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      -
        name: Set up bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.1"

      -
        name: Install dependencies
        run: bun install

      - 
        name: Build Vite frontend for production with bun runtime
        run: bun run build
          
      -
        name: Check that go build works
        run: go build -o norsky
