name: Publish

on:
  push:
    tags:
      - v*
    branches-ignore:
      - '**'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.1"
      
      -
        name: Set up bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      -

        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Install dependencies
        run: bun install

      - 
        name: Build Vite frontend for production with bun runtime
        env:
          ## This is the URL the Solid app will use to make API calls
          VITE_API_URL: https://norsky.snorre.io
        run: bun run 
        

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
